# Generated by Django 3.2.5 on 2021-07-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phonenumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdivision', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=150)),
                ('surname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
                ('oficial_telephone', models.CharField(max_length=20)),
                ('landline_telephone', models.CharField(max_length=20)),
                ('service_fax', models.CharField(max_length=20)),
                ('mobile_telephone', models.CharField(max_length=12)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
            ],
        ),
    ]
