# Generated by Django 3.2.5 on 2021-07-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Наименование категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='phonenumber',
            options={'ordering': ['-create_at'], 'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='service_email',
            field=models.CharField(blank=True, max_length=150, verbose_name='почта'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='опубликовано'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='landline_telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='городской телефон'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='mobile_telephone',
            field=models.CharField(blank=True, max_length=12, verbose_name='мобильный телефон'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='name',
            field=models.CharField(max_length=20, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='note',
            field=models.TextField(blank=True, verbose_name='примечание'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='oficial_telephone',
            field=models.CharField(max_length=20, verbose_name='служебный телефон'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='position',
            field=models.CharField(max_length=150, verbose_name='должность'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='second_name',
            field=models.CharField(max_length=20, verbose_name='отчество'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='service_fax',
            field=models.CharField(blank=True, max_length=10, verbose_name='служебный факс'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='subdivision',
            field=models.CharField(max_length=150, verbose_name='подразделение'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата и время обновления'),
        ),
    ]
