# Generated by Django 3.2.5 on 2021-07-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0002_auto_20210709_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='mobile_telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='мобильный телефон'),
        ),
    ]
