# Generated by Django 3.2.5 on 2021-07-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0003_alter_phonenumber_mobile_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='service_fax',
            field=models.CharField(blank=True, max_length=20, verbose_name='служебный факс'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='subdivision',
            field=models.CharField(max_length=150, verbose_name='подотдел'),
        ),
    ]
