# Generated by Django 3.2.5 on 2021-07-16 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0005_auto_20210716_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilitaryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Войсковая часть')),
            ],
            options={
                'verbose_name': 'Войсковая часть',
                'verbose_name_plural': 'Воинские части',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='subdivision',
            field=models.CharField(blank=True, max_length=150, verbose_name='подотдел'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='military_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='phonebook.militaryunit', verbose_name='Войсковая часть'),
        ),
    ]
