# Generated by Django 3.2.5 on 2021-07-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0007_auto_20210716_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militaryunit',
            name='title',
            field=models.CharField(db_index=True, max_length=7, verbose_name='№ в\\ч'),
        ),
    ]
